### ISSUE TITLE
Unable to distill / barrel-age brews...

### ISSUE THREAD

**Issue by Vutka1** [BlueMoonVineyard/BreweryNG#9]
So, I was very happy when I saw this brewery fork that constantly updates with a new features, unlike the original plugin. However, I've been strugling trying to make it run properly.

I've been testing some brews when I noticed that plugin is unable to distill brews or age them in barrels. When distillation row ends, instead of giving a completed brew it simply starts again, sending an error to console. In case of aging, after 1 barrel year passes the barrel simply refuses to open, also giving a console error in process. I have no issues brewing anything that doesn't require distillating or aging (e.g. vanilla-config potato soup).

- Also, for some reason every time I put a brew into a brewing stand or barrel, plugin spams messages to console about checking the liquid types of every existing drink, or something like that. Don't know if these 2 issues are connected to each other.

Both the messages spam and the error are provided below:
![CunoooNI3PdF3pzjCK802nxOrQbcH2FFogqXSWfjSWE1PzNSMy3IGTcXK42QdHkqngQdAkpBJI4Yc5gOk1T1Vj9h](https://user-images.githubusercontent.com/93795732/219696678-34a2fe9b-dc71-488d-82b3-75273004902d.jpg)
I have little to no knowledge in Java, so this error doesn't make any sense to me.
If needed, I can provide the error in a text format.

What I have already tried, and it didn't help:
Changing server Java version (tried 17, 18 and 19),
Changing server cores (tried Paper, Pufferfish, PurPur. All on 1.18.2),
Using different fork versions (1.3.0 and 1.2.1),
Using fork together with the original plugin,
Disabling all other plugins,
Deleting all the files and testing it on a clean server,
Clearing worlddata.yml, data.yml and config.yml that were left from the original brewery.

**Comment by Smudgge** [comment]
We are having a similar issue

**Comment by Smudgge** [comment]
**From a player on the server**

While using the brewery plugin today, I put brews in the small custom barrels and they worked fine up until the brews were close to a year done of aging. Then I couldn't open or access the custom barrels with brews in them at all, and the vanilla barrels weren't aging brews.

The cooking process and cauldrons worked fine. The custom barrels worked fine without brews in them (you can access them and put brews in and out). Custom barrels break once the brews inside age a year. Vanilla barrels just don't age brews.

Vanilla barrels still recognize the brews being put in, keeping you from putting in more than 6 brews at a time as normal, but after 50 minutes of sitting in the vanilla barrels, none of my brews aged (they should have aged 2 years now)
Creating the custom Barrels still works. I have not tried brewing since the plugin was updated, so old custom barrels may need rebuilt, which im going to test now (building a new custom barrel and seeing if aging a brew will work in it).

Testing it with a newly made custom barrel also had the same problem.

**Comment by sowelipililimute** [comment]
a fix for this is underway, https://github.com/BlueMoonVineyard/BreweryNG/pull/10

**Comment by Vutka1** [comment]
@pontaoski , so I tested the pull request .jar, and it no longer spams in console and distills/ages brews without errors, however if I try to distill something that was brewed too inaccurate (e.g. tequila that was brewed for 26+ minutes, instead of needed 15, or vodka that has only 1 potato in it), it once again repeats the distill row infinitely w/o final result and sends an error to console.

![JToK63KlzWbV8MD_EMSqaUk2ozNMRGW8x01qWLRJvlhoU23BrVF7txGzz5Z0NnTUgB35O1eIpgZy5HMPo8bZB2fH](https://user-images.githubusercontent.com/93795732/220319755-dbcf2259-1ff4-45a4-b37c-1abcb3d99e41.jpg)

**Comment by sowelipililimute** [comment]
can you open a follow-up issue? that looks to be something else from the issue i fixed with #10.
